name: Spring Boot App Test

on: 
  push:
    branches: [ master ]
    paths:
      - src/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and test with Maven
        run: mvn clean install
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    env:
      DIRNAME: myapp
      STACK_NAME: psgen-cdk
      CLUSTER_NAME: psgen-cdk-cluster
      SERVICE_NAME: psgen-cdk-service
      PORT_NUMBER: 8080
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_NUMBER }}
      CDK_DEFAULT_REGION: us-east-2
      CDK_INFRASTRUCTURE_REPO: cdk-infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Create and move files into $DIRNAME
        run: |
          mkdir $DIRNAME
          ls | grep -v $DIRNAME | xargs mv -t $DIRNAME
      - name: Cloning AWS CDK infrastructure
        run: git clone https://github.com/jsx101/cdk-infrastructure.git
      - name: Move $DIRNAME into cdk app and cd into it
        run: mv $DIRNAME $CDK_INFRASTRUCTURE_REPO
      - name: npm install
        run: cd $CDK_INFRASTRUCTURE_REPO && npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install 'cdk' command
        run: npm i -g aws-cdk
      - name: Clean install Spring Boot app for Dockerization
        run: cd $CDK_INFRASTRUCTURE_REPO/$DIRNAME && mvn clean install
      - name: cdk deploy
        run: cd $CDK_INFRASTRUCTURE_REPO && cdk deploy --context stackName=$STACK_NAME --context clusterName=$CLUSTER_NAME --context serviceName=$SERVICE_NAME --context assetFolder=$DIRNAME --context port=$PORT_NUMBER --require-approval never